spring:
  profiles:
    include:
    - common-dev

mybatis:
  type-aliases-package: com.edu.scnu.idnt.bean
  mapper-locations: classpath:mapper/**.xml,classpath:mapper/ext/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
