############################################################################
#
#  redis 相关配置
#
############################################################################
spring:
  redis:
    # redis 数据库索引，默认为0
    database: 1
    host: 192.168.56.101
    port: 6379
    password: 
    # 连接超时时间(毫秒)
    timeout: 200
    pool:
      # 连接池最大连接数限制
      max-active: 1000
      # 连接池最大阻塞时间  -1表示不限制
      max-wait: -1
      # 连接池最大空闲连接
      max-idle: 10
      # 连接池最小空闲连接
      min-idle: 2
      
resource:
  savePath: G:\\WebSpace\\myJee\\resources\\
  visitPath: http://gkzy.gdzhaosheng.com/resources/
  